### ISSUE TITLE
Fatal error when going to the example page

### ISSUE THREAD

**Issue by RoySegall** [Plug-Drupal/plug#20]
I'm trying this module and when enabling the module example module and i get:
![image](https://cloud.githubusercontent.com/assets/1222368/5900096/6f4f4d0a-a56d-11e4-9bee-eb9461ffa26e.png)
Fatal error: Class 'Drupal\Component\Plugin\PluginManagerBase' not found in /var/www/html/drupal/sites/all/modules/plug/src/Core/Plugin/DefaultPluginManager.php on line 22

**Comment by e0ipso** [comment]
This is probably due to registry issues. Try with drush really or drush cc all. 

Also, install the latest dev

**Comment by RoySegall** [comment]
I cloned the dev branches of xautoload and this one.

**Comment by e0ipso** [comment]
Did clearing caches help at all?

**Comment by RoySegall** [comment]
I pulled and the modules again and it worked in the office. I'll check this at home and let you know.

**Comment by RoySegall** [comment]
On my ubuntu at my office it's working but on my mac at home no.

**Comment by e0ipso** [comment]
@RoySegall any more details on the not working environment? This should be a Drupal thing nothing related to the OS.

I would advise you to run `drush rr`, `drush rr --fire-bazooka` and/or `drush cc all`.

You'll need https://www.drupal.org/project/registry_rebuild

**Comment by RoySegall** [comment]
Even with a fresh install?

**Comment by e0ipso** [comment]
Sure.

BTW, this is the latest -dev version that you're trying on your mac, right?

**Comment by RoySegall** [comment]
Not the dev version but 7.34. On my ubuntu it's the same. I'll try tonight to pull the dev version of drupal on my mac and i'll update.

**Comment by e0ipso** [comment]
Sorry I meant the latest version (update with the latest changes) of the Plug module.

**Comment by RoySegall** [comment]
i cloned and pull dev. Maybe clearing the drush cache would work.

**Comment by q0rban** [comment]
I would try calling `drush registry-rebuild`.

**Comment by RoySegall** [comment]
@q0rban 10x. Will check this at home and i'll update.

**Comment by DavidHernandez** [comment]
I had this issue when I installed plug for the first time. I solved it following the installation instructions:

drush composer-manager update

**Comment by q0rban** [comment]
@RoySegall, oh, sorry! I missed that you had already tried that.

**Comment by RoySegall** [comment]
@q0rban I don't think i rebuild the registry. I can give a try to any thing that will fix this on my mac.

**Comment by e0ipso** [comment]
> I had this issue when I installed plug for the first time. I solved it following the installation instructions:
> 
> drush composer-manager update

Did you run composer to bring in the dependencies?

**Comment by RoySegall** [comment]
Yes.

**Comment by RoySegall** [comment]
Sorry for my french but: God demet! after increasing the memory limit for the CLI and trying any command above what helped is: xautoload dev version, plug dev version(both downloaded with drush, not cloning them) i run `drush composer-manager update` and now i can access the example page of plug.

Closing this one and i'm grateful to everyone that joined this ticket.
