### ISSUE TITLE
Find out what tests we should write.

### ISSUE THREAD

**Issue by e0ipso** [Plug-Drupal/plug#5]
I just care about testing our own code. I want to treat the code from composer as _already tested_.

**Comment by e0ipso** [comment]
@plopesc any ideas about this one?

**Comment by plopesc** [comment]
Yep. We could try to use some kind of travis testing for d7-plugins repo. But it should work out of the box given that comes directly from D8 core.
About this repo, we could just start doing a simple test on plug_example that checks on example pages that results are the expected.
Also we could add a plug_test module implementing alter hooks (as in #9) more in-depth. This module could add more plugins and test that depending on this module status, those plugins are discoverred or not.
We could add basic tests on plug module related to Util\Module.

More ideas @mateu-aguilo-bosch ?
If you find these proposed tests useful, I can start to implement them tomorrow morning :)
